repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=10240']
    -   id: check-builtin-literals
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: check-json
    -   id: check-xml

- repo: https://github.com/gitleaks/gitleaks.git
  rev: v8.18.4
  hooks:
    - id: gitleaks
      args: ["--verbose"]

- repo: local
  hooks:
    - id: isort
      name: isort
      entry: poetry run isort
      language: system
      types: [ python ]
    - id: ruff-format
      name: ruff-format
      entry: ruff format
      language: system
      pass_filenames: false
      types: [ python ]
    - id: ruff-check
      name: ruff-check
      entry: ruff check --fix
      language: system
      pass_filenames: false
      types: [ python ]
    - id: pylint
      name: pylint
      entry: poetry run pylint
      language: system
      types: [ python ]
    - id: mypy
      name: mypy
      entry: poetry run mypy
      language: system
      types: [ python ]
